# https://github.com/brigade/scss-lint/blob/master/lib/scss_lint/linter/README.md
---
preprocess_command: "gsed '1{/^---$/{:a N;/---$/!ba;d}}'"
linters:
    BorderZero:
        convention: none
    DuplicateProperty:
        ignore_consecutive: true
    HexNotation:
        style: uppercase
    Indentation:
        width: 4
    LeadingZero:
        style: include_zero
    NestingDepth:
        max_depth: 5
    PropertySortOrder:
        order: smacss
        ignore_unspecified: true
    QualifyingElement:
        allow_element_with_attribute: true
        allow_element_with_class: true
        allow_element_with_id: true
    SelectorDepth:
        max_depth: 5
    StringQuotes:
        style: double_quotes
---
